#!/bin/bash

##
# created by Tim Meusel
# with help from Silvio Knizek
##

# this script will download our installimage config

# get our config
config='/usr/local/bin/config_live.sh'
if [ -n "$config" ] && [ -e "$config" ]; then
  # shellcheck disable=SC1090
  . "${config}"
else
  echo "Error: ${config} file isn't available"
  exit 1
fi

set -e -u

# currently we need the mac from the interface we used for booting, not the first one
#mac="$(ifdata -ph eth0 | awk '{gsub(":",""); print tolower($1)}')"
mac=$(awk 'BEGIN {FS="="; RS=" ";} { if ($1 ~ /BOOTIF/) {gsub(/^[^-]+-/, "", $2); gsub(/-/, ":", $2); print tolower($2)}}' /proc/cmdline)

url="${CONFIG_PROTO}://${CONFIG_SERVER}/${CONFIG_PATH}/${mac}/${CONFIG_FILE}"

wget "${url}" --retry-connrefused -q -O /root/config.cfg
if [ $? != 0 ]; then
  echo "failed to download config"
  exit 1
fi

# start installimage with our config
/root/.installimage/installimage.in_screen -c config.cfg -a
